// @flow

const fs = require('fs')
const path = require('path')

const inputFile = path.join(__dirname, '..', 'index.d.ts')
const outputFile = path.join(__dirname, '..', 'dist', 'index.js.flow')

const inputStr = fs.readFileSync(inputFile).toString()

const HEADER = '// @flow\n// AUTOGENERATED, edit index.d.ts instead\n\n'

const outputStr = HEADER + inputStr
  .replace(/readonly /g, '+')
  .replace(/export function/g, 'declare export function')
  .replace(/export const/g, 'declare export const')
  .replace(/export class/g, 'declare export class')
  .replace(/(?:private )?constructor\((.+)\);/g, 'constructor($1): void;')
  .replace(/: unknown/g, ': mixed')
  .replace(/AsyncIterableIterator</g, 'AsyncIterator<')

fs.writeFileSync(outputFile, outputStr)
